version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
  app:
    container_name: member-app
    image: openjdk:17-jdk
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["./msa-iamhere-member/gradlew", "bootrun"]
    depends_on:
      - db
    restart: always
networks:
  backend: