spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/Iamhere?useSSL=false&characterEncoding=UTF-8
    username: admin
    password: asdf1234
